import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { GENERATED_LEVELS } from '../game/core/levels-manifest.gen'
import { parseXsbSetLevels } from '../game/core/xsb-parser'
import { PACKS, type LevelMeta } from '../game/core/types'
import { generate, levelHash, solveLevel, type SolveResult } from './levelgen-lib'

const root = process.cwd()
const readLevel = (file: string) => parseXsbSetLevels(readFileSync(resolve(root, 'public' + file), 'utf8'))[0]!.level
const enhanced = process.argv.includes('--enhance')
const write = process.argv.includes('--write')
const seen = new Set<string>()
const metas: LevelMeta[] = []
const names = ['窄巷借位', '转角让行', '回字工坊', '双门调度', '先退后进', '交错货仓', '留出退路', '封口顺序', '环路交换', '深巷搬运', '最后一格', '大师收官']
let seed = 23092026
let made = 0
const deadline = Date.now() + 240_000
for (const original of GENERATED_LEVELS) {
  let meta = { ...original }
  let level = readLevel(meta.file)
  let result: SolveResult | null = null
  if (enhanced && meta.pack === 'hard' && meta.num > 38) {
    const file = `/levels/hard/challenge-${meta.num - 38}.xsb`
    if (existsSync(resolve(root, 'public' + file))) {
      level = readLevel(file)
      result = solveLevel(level, 600_000, 15_000)
    } else {
      while (Date.now() < deadline) {
        seed++
        const size = 7 + seed % 3
        const text = generate({ w: size, h: size + seed % 2, boxes: 3 + seed % 2, interiorWalls: 6 + seed % 9, pulls: 35 + seed % 35, seed })
        if (!text) continue
        const candidate = parseXsbSetLevels(text)[0]!.level
        const hash = levelHash(candidate)
        if (seen.has(hash)) continue
        const solved = solveLevel(candidate, 100_000, 800)
        if (!solved || solved.pushes < 14 || solved.moves < 45 || solved.moves > 115) continue
        level = candidate
        result = solved
        if (write) writeFileSync(resolve(root, 'public' + file), `Challenge ${meta.num - 38}\n${text}\n`)
        break
      }
    }
    if (!result) throw new Error(`Challenge generation budget exhausted at ${meta.id}; rerun to resume`)
    meta = { ...meta, id: `${meta.id}-r2`, file, name: names[meta.num - 39]! }
    made++
    console.log(`CHALLENGE ${made}: ${level.width}x${level.height}, ${result.pushes} pushes, ${result.moves} moves`)
  }
  result ??= solveLevel(level, 600_000, 15_000)
  if (!result) throw new Error(`Unsolved: ${meta.id}`)
  const hash = levelHash(level)
  if (seen.has(hash)) throw new Error(`Equivalent duplicate: ${meta.id}`)
  seen.add(hash)
  const challenge = result.pushes * 4 + result.moves + level.boxStarts.length * 6
  metas.push({
    ...meta,
    par: Math.max(original.par ?? 0, Math.ceil(result.moves * 1.25)),
    challenge,
    minPushes: result.pushes,
    solutionMoves: result.moves,
    boxCount: level.boxStarts.length,
  })
}
const ordered = PACKS.flatMap(pack => {
  const rows = metas.filter(m => m.pack === pack.id).sort((a, b) => a.challenge! - b.challenge! || a.num - b.num)
  return rows.map((meta, i) => ({
    ...meta,
    num: i + 1,
    stage: ['起步', '进阶', '挑战'][Math.min(2, Math.floor(i / rows.length * 3))],
  }))
})
for (const pack of PACKS) {
  const rows = ordered.filter(m => m.pack === pack.id)
  console.log(`${pack.id}: ${rows.length} unique levels; score ${rows[0]!.challenge}-${rows.at(-1)!.challenge}; pushes ${Math.min(...rows.map(m => m.minPushes!))}-${Math.max(...rows.map(m => m.minPushes!))}; reference moves ${Math.min(...rows.map(m => m.solutionMoves!))}-${Math.max(...rows.map(m => m.solutionMoves!))}`)
}
if (write) {
  writeFileSync(resolve(root, 'game/core/levels-curriculum.gen.ts'),
    `// Generated by scripts/curate-levels.ts. IDs preserve board identity across reordering.\nimport type { LevelMeta } from './types'\nexport const CURATED_LEVELS: LevelMeta[] = ${JSON.stringify(ordered, null, 2)}\n`)
}
console.log(`PASS: ${seen.size} solvable, symmetry-distinct boards; ${made} enhanced challenges`)
